chall/urls.py
from django.urls import path
from django.contrib import admin
from .views import chall

urlpatterns = [
    path('', chall, name = 'chall'),
    path('admin/', admin.site.urls)
]

djangohaz/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),

    
]

home/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chall', include('chall.urls')),
    path('', home, name = 'home'),
]

chall/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.
class UserInput(models.Model):
    status_user = models.CharField(max_length=300, blank = False, verbose_name=u" ")
    upload_time = models.DateTimeField(auto_now_add = True, null = True)

    def __str__(self):
        return self.status_user

home/forms.py
from django import forms
from .models import UserInput

class status_input(forms.Form):
    # class Meta:
    #     model = input
    #     fields = ['status_user']
    #     widgets = {
    #         'status_user' : forms.CharField(attrs={'placeholder' : 'Masukkan status anda','style' : 'border:0; width:100%'})
    #     }
    status_user = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : '',
        'type' : 'text',
        'maxlength' : '',
        'required' : True,
        'style' : '',
        'label' : '',
    }))

chall/views.py
from django.shortcuts import render

# Create your views here.

def chall(request):
    return render(request, 'chall.html')

home/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import UserInput

# Create your views here.
# def home(request):
#     return render(request, 'index.html')

def home(request):
    if request.method == "POST":
        form = status_input(request.POST)
        if (form.is_valid()):
            status = UserInput()
            status.status_user = form.cleaned_data['status_user']
            status.save()
        return redirect('/')
    else:
        form = status_input()
        status = UserInput.objects.all().order_by('-upload_time')
        response = {'status' : status, 'form': form}
        return render(request, 'indexnew.html', response)

chall/templates/chall.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Challenge</title>
</head>

<body>
    <h1 style="color:red; font-weight:bolder;">NPM: 1906316793</h1>
</body>

</html>

chall/templates/snippets/navbar.html
{% load static %}

<header>
    <nav class="Navbar">
        <img alt="" src="{% static 'img/HazEyesSimple (White).svg' %}" class="NavbarLogo">
        <ul class="NavbarPages">
            <li>
                {% for link,name in nav%}
                <a href="{{link}}">{{name}}</a> {% endfor %}
            </li>

        </ul>
    </nav>
</header>

home/templates/indexnew.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css'%}" type="text/css">
    <title>Document</title>
</head>

<body>
    {% include 'snippets/navbar.html'%}

    <section class="grid-autofit-la bg-black ">
        <div class="container-100p flexrow-cccl margin-1em">
            <div>
                <h1>
                    Tell me about your thoughts!
                </h1>
                <br>
            </div>
            <div class="">
                <form method="POST" class="flexrow-cccl">
                    <div class="">
                        {% csrf_token %}
                        <input type="text" name="status_user" class="bg-white" placeholder="I Hate Monday..." required="" label="" id="id_status_user">
                        <br>
                        <input type="Submit" name="button_input" value="Share it Share it!!" class="cta-green">
                    </div>
                </form>
            </div>
        </div>
        <div class="container-100p flexrow-ccc">
            <h1>Stories</h1>
            <br>
            <div class="container-50vh-nopad-fixed overflowy-scroll">
                {% for i in status %}
                <div class="flexible-cards bg-white flexrow-llcl margin-1em">
                    <p style="font-size: 1em;">
                        {{ i.status_user }}
                    </p>
                    <br>
                    <p style="font-size: 0.7em; color:rgba(0,0,0,0.5)">{{i.upload_time}}</p>
                </div>
                <br> {% endfor %}
            </div>
        </div>
    </section>
    <section>
    </section>

</body>

</html>

home/templates/snippets/navbar.html
{% load static %}

<header>
    <nav class="Navbar">
        <img alt="" src="{% static 'img/HazEyesSimple (White).svg' %}" class="NavbarLogo">
        <ul class="NavbarPages">
            <li>
                {% for link,name in nav%}
                <a href="{{link}}">{{name}}</a> {% endfor %}
            </li>

        </ul>
    </nav>
</header>